import { UnscheduledLessonRow } from "../unscheduledLessonsListing.api";

export const mockUnscheduledLessonData: UnscheduledLessonRow[] = [
  // Active lessons (expiryDate in the future)
  {
    id: 1,
    student: "Test student25",
    program: "xSaxophone",
    teacher: "Test teacherseng",
    duration: "00:30",
    date: "Oct 02, 2025",
    expiryDate: "Dec 31, 2025",
  },
  {
    id: 2,
    student: "Jonathan Toews",
    program: "Guitar Core",
    teacher: "Art Tatum",
    duration: "00:30",
    date: "Oct 10, 2025",
    expiryDate: "Jan 08, 2026",
  },
  {
    id: 3,
    student: "Test studentseng",
    program: "xPiano Hybrid",
    teacher: "Test teacherseng",
    duration: "00:30",
    date: "Dec 05, 2025",
    expiryDate: "Mar 05, 2026",
  },
  {
    id: 4,
    student: "abcd bande",
    program: "xGuitar Core",
    teacher: "Eddie Vedder",
    duration: "00:30",
    date: "Dec 15, 2025",
    expiryDate: "Mar 15, 2026",
  },
  {
    id: 5,
    student: "abcd bande",
    program: "xPiano Hybrid",
    teacher: "Art Tatum",
    duration: "00:30",
    date: "Dec 15, 2025",
    expiryDate: "Mar 15, 2026",
  },
  {
    id: 6,
    student: "Anwar Raja",
    program: "xPiano Hybrid",
    teacher: "Alexander Hamilton",
    duration: "00:30",
    date: "Dec 18, 2025",
    expiryDate: "Mar 18, 2026",
  },
  {
    id: 7,
    student: "Sarah Johnson",
    program: "Violin",
    teacher: "Mozart",
    duration: "00:45",
    date: "Nov 20, 2025",
    expiryDate: "Feb 20, 2026",
  },
  {
    id: 8,
    student: "Michael Chen",
    program: "Drums",
    teacher: "John Bonham",
    duration: "01:00",
    date: "Nov 25, 2025",
    expiryDate: "Feb 25, 2026",
  },
  {
    id: 9,
    student: "Emily Davis",
    program: "Flute",
    teacher: "James Galway",
    duration: "00:30",
    date: "Dec 01, 2025",
    expiryDate: "Mar 01, 2026",
  },
  {
    id: 10,
    student: "David Wilson",
    program: "Trumpet",
    teacher: "Louis Armstrong",
    duration: "00:45",
    date: "Dec 10, 2025",
    expiryDate: "Mar 10, 2026",
  },
  {
    id: 11,
    student: "Lisa Anderson",
    program: "Voice",
    teacher: "Maria Callas",
    duration: "01:00",
    date: "Dec 12, 2025",
    expiryDate: "Mar 12, 2026",
  },
  {
    id: 12,
    student: "Robert Brown",
    program: "Bass Guitar",
    teacher: "Jaco Pastorius",
    duration: "00:45",
    date: "Dec 20, 2025",
    expiryDate: "Mar 20, 2026",
  },
  {
    id: 13,
    student: "Jennifer Martinez",
    program: "Piano",
    teacher: "Vladimir Horowitz",
    duration: "01:00",
    date: "Dec 22, 2025",
    expiryDate: "Mar 22, 2026",
  },
  {
    id: 14,
    student: "Christopher Lee",
    program: "Guitar",
    teacher: "Jimi Hendrix",
    duration: "00:30",
    date: "Dec 25, 2025",
    expiryDate: "Mar 25, 2026",
  },
  {
    id: 15,
    student: "Amanda Taylor",
    program: "Cello",
    teacher: "Yo-Yo Ma",
    duration: "00:45",
    date: "Dec 28, 2025",
    expiryDate: "Mar 28, 2026",
  },
  // Inactive lessons (expiryDate in the past)
  {
    id: 16,
    student: "Thomas White",
    program: "Piano",
    teacher: "Beethoven",
    duration: "00:30",
    date: "Sep 15, 2024",
    expiryDate: "Dec 15, 2024",
  },
  {
    id: 17,
    student: "Patricia Harris",
    program: "Violin",
    teacher: "Paganini",
    duration: "00:45",
    date: "Aug 20, 2024",
    expiryDate: "Nov 20, 2024",
  },
  {
    id: 18,
    student: "Daniel Moore",
    program: "Guitar",
    teacher: "Eric Clapton",
    duration: "01:00",
    date: "Jul 10, 2024",
    expiryDate: "Oct 10, 2024",
  },
  {
    id: 19,
    student: "Nancy Jackson",
    program: "Drums",
    teacher: "Neil Peart",
    duration: "00:30",
    date: "Jun 05, 2024",
    expiryDate: "Sep 05, 2024",
  },
  {
    id: 20,
    student: "Kevin Thompson",
    program: "Bass",
    teacher: "Flea",
    duration: "00:45",
    date: "May 18, 2024",
    expiryDate: "Aug 18, 2024",
  },
  {
    id: 21,
    student: "Michelle Garcia",
    program: "Flute",
    teacher: "Jean-Pierre Rampal",
    duration: "00:30",
    date: "Apr 12, 2024",
    expiryDate: "Jul 12, 2024",
  },
  {
    id: 22,
    student: "Steven Rodriguez",
    program: "Trumpet",
    teacher: "Miles Davis",
    duration: "01:00",
    date: "Mar 25, 2024",
    expiryDate: "Jun 25, 2024",
  },
  {
    id: 23,
    student: "Karen Lewis",
    program: "Voice",
    teacher: "Luciano Pavarotti",
    duration: "00:45",
    date: "Feb 14, 2024",
    expiryDate: "May 14, 2024",
  },
  {
    id: 24,
    student: "Brian Walker",
    program: "Saxophone",
    teacher: "John Coltrane",
    duration: "00:30",
    date: "Jan 08, 2024",
    expiryDate: "Apr 08, 2024",
  },
  {
    id: 25,
    student: "Laura Hall",
    program: "Piano",
    teacher: "Chopin",
    duration: "01:00",
    date: "Dec 20, 2023",
    expiryDate: "Mar 20, 2024",
  },
  {
    id: 26,
    student: "Jason Young",
    program: "Guitar",
    teacher: "B.B. King",
    duration: "00:45",
    date: "Nov 15, 2023",
    expiryDate: "Feb 15, 2024",
  },
  {
    id: 27,
    student: "Rebecca King",
    program: "Cello",
    teacher: "Mstislav Rostropovich",
    duration: "00:30",
    date: "Oct 10, 2023",
    expiryDate: "Jan 10, 2024",
  },
  {
    id: 28,
    student: "Matthew Wright",
    program: "Drums",
    teacher: "Buddy Rich",
    duration: "01:00",
    date: "Sep 05, 2023",
    expiryDate: "Dec 05, 2023",
  },
  {
    id: 29,
    student: "Stephanie Lopez",
    program: "Violin",
    teacher: "Itzhak Perlman",
    duration: "00:45",
    date: "Aug 01, 2023",
    expiryDate: "Nov 01, 2023",
  },
  {
    id: 30,
    student: "Ryan Scott",
    program: "Bass Guitar",
    teacher: "Victor Wooten",
    duration: "00:30",
    date: "Jul 20, 2023",
    expiryDate: "Oct 20, 2023",
  },
];


