# syntax=docker/dockerfile:1.6
FROM node:20-alpine

WORKDIR /apps

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_LEGACY_URL
ARG NEXT_PUBLIC_ENV
ARG NEXT_PUBLIC_OPENREPLAY_PROJECT_KEY
ARG NEXT_PUBLIC_OPENREPLAY_INGEST_POINT

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_LEGACY_URL=$NEXT_PUBLIC_LEGACY_URL
ENV NEXT_PUBLIC_ENV=$NEXT_PUBLIC_ENV
ENV NEXT_PUBLIC_OPENREPLAY_PROJECT_KEY=$NEXT_PUBLIC_OPENREPLAY_PROJECT_KEY
ENV NEXT_PUBLIC_OPENREPLAY_INGEST_POINT=$NEXT_PUBLIC_OPENREPLAY_INGEST_POINT

COPY package.json yarn.lock ./

RUN --mount=type=cache,target=/usr/local/share/.cache/yarn \
    yarn install --frozen-lockfile

COPY . .

RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"]
