import { ItemRow } from "../itemsListing.api";

export const mockItemData: ItemRow[] = [
  {
    id: 1,
    code: "LESSON",
    itemCategory: "Lesson",
    description: "LESSON",
    price: 0.00,
    royaltyFree: "No",
    tax: "No Tax",
    status: "Enable",
  },
  {
    id: 2,
    code: "OPENING BALANCE",
    itemCategory: "Opening Balance",
    description: "Opening Balance",
    price: 0.00,
    royaltyFree: "No",
    tax: "No Tax",
    status: "Enable",
  },
  {
    id: 3,
    code: "MBOOK",
    itemCategory: "Methods Books",
    description: "Method Book #1",
    price: 15.99,
    royaltyFree: "No",
    tax: "GST Only",
    status: "Enable",
  },
  {
    id: 4,
    code: "BOOK",
    itemCategory: "Non Method Books",
    description: "Book",
    price: 18.99,
    royaltyFree: "No",
    tax: "Default",
    status: "Enable",
  },
  {
    id: 5,
    code: "RENT",
    itemCategory: "Rentals",
    description: "Rental Charge",
    price: 20.00,
    royaltyFree: "No",
    tax: "Default",
    status: "Enable",
  },
  {
    id: 6,
    code: "GUITAR",
    itemCategory: "Smallware",
    description: "Guitar",
    price: 100.00,
    royaltyFree: "No",
    tax: "Default",
    status: "Enable",
  },
  {
    id: 7,
    code: "MNP01",
    itemCategory: "Methods Books",
    description: "Music Notes for Piano Lesson -01",
    price: 110.00,
    royaltyFree: "No",
    tax: "Default",
    status: "Enable",
  },
  {
    id: 8,
    code: "MNP02",
    itemCategory: "Methods Books",
    description: "Music Notes for Piano Lesson -02",
    price: 120.00,
    royaltyFree: "No",
    tax: "Default",
    status: "Enable",
  },
  {
    id: 9,
    code: "MNP03",
    itemCategory: "Methods Books",
    description: "Music Notes for Piano Lesson -03",
    price: 130.00,
    royaltyFree: "No",
    tax: "Default",
    status: "Enable",
  },
  {
    id: 10,
    code: "MNP04",
    itemCategory: "Methods Books",
    description: "Music Notes for Piano Lesson -04",
    price: 140.00,
    royaltyFree: "No",
    tax: "Default",
    status: "Enable",
  },
  {
    id: 11,
    code: "MNP05",
    itemCategory: "Methods Books",
    description: "Music Notes for Piano Lesson -05",
    price: 150.00,
    royaltyFree: "No",
    tax: "Default",
    status: "Enable",
  },
  {
    id: 12,
    code: "MNP06",
    itemCategory: "Methods Books",
    description: "Music Notes for Piano Lesson -06",
    price: 160.00,
    royaltyFree: "No",
    tax: "Default",
    status: "Enable",
  },
  {
    id: 13,
    code: "VIOLIN",
    itemCategory: "Smallware",
    description: "Violin Rental",
    price: 75.00,
    royaltyFree: "Yes",
    tax: "GST Only",
    status: "Enable",
  },
  {
    id: 14,
    code: "PIANO",
    itemCategory: "Rentals",
    description: "Piano Rental",
    price: 200.00,
    royaltyFree: "No",
    tax: "Default",
    status: "Enable",
  },
  {
    id: 15,
    code: "DRUM",
    itemCategory: "Smallware",
    description: "Drum Set",
    price: 250.00,
    royaltyFree: "No",
    tax: "Default",
    status: "Enable",
  },
  {
    id: 16,
    code: "SHEET01",
    itemCategory: "Non Method Books",
    description: "Sheet Music Collection #1",
    price: 25.99,
    royaltyFree: "Yes",
    tax: "GST Only",
    status: "Enable",
  },
  {
    id: 17,
    code: "SHEET02",
    itemCategory: "Non Method Books",
    description: "Sheet Music Collection #2",
    price: 29.99,
    royaltyFree: "Yes",
    tax: "GST Only",
    status: "Enable",
  },
  {
    id: 18,
    code: "ACCORDION",
    itemCategory: "Smallware",
    description: "Accordion",
    price: 180.00,
    royaltyFree: "No",
    tax: "Default",
    status: "Disable",
  },
  {
    id: 19,
    code: "FLUTE",
    itemCategory: "Smallware",
    description: "Flute",
    price: 95.00,
    royaltyFree: "No",
    tax: "Default",
    status: "Enable",
  },
  {
    id: 20,
    code: "SAXOPHONE",
    itemCategory: "Smallware",
    description: "Saxophone",
    price: 220.00,
    royaltyFree: "No",
    tax: "Default",
    status: "Enable",
  },
];

