import type { EnrolmentInfo } from "../types";

export const mockEnrolmentDetails: EnrolmentInfo = {
  details: {
    id: 31166,
    program: "40th Anniversary Piano",
    teacher: "Sushanthi s Aloysius",
    rate: "$20.00",
    rateFromDate: "Nov 14, 2025",
    rateToDate: "Feb 28, 2026",
    autoRenewal: "Disabled",
    duration: "01:00",
    student: "stu1 nov12",
    studentId: 123,
    customer: "test nov12",
    customerId: 456,
    online: false,
  },
  discounts: {
    pfDiscount: "Not set",
    multipleEnrolDiscount: "Not set",
  },
  paymentFrequency: {
    paymentFrequency: "Monthly",
  },
  schedule: {
    day: "Friday",
    time: "11:30 AM",
    startDate: "Nov 14, 2025",
    endDate: "Feb 06, 2026",
  },
  scheduleHistory: [
    {
      id: 1,
      date: "Nov 14, 2025 - Dec 31, 2025",
      day: "Friday",
      time: "11:30 AM",
      duration: "01:00",
      teacher: "Test teacherseng",
    },
    {
      id: 2,
      date: "Jan 01, 2026 - Feb 06, 2026",
      day: "Friday",
      time: "11:30 AM",
      duration: "01:00",
      teacher: "Sushanthi s Aloysius",
    },
  ],
  lessons: [
    {
      id: 1,
      dueDate: "Nov 15, 2025",
      date: "Dec 26, 2025 @ 11:30 AM",
      duration: "01:00",
      status: "Scheduled",
      price: "$20.00",
      owing: "$20.00",
      online: false,
    },
    {
      id: 2,
      dueDate: "Dec 15, 2025",
      date: "Jan 02, 2026 @ 11:30 AM",
      duration: "01:00",
      status: "Scheduled",
      price: "$20.00",
      owing: "$20.00",
      online: false,
    },
    {
      id: 3,
      dueDate: "",
      date: "Jan 09, 2026 @ 11:30 AM",
      duration: "01:00",
      status: "Scheduled",
      price: "$20.00",
      owing: "$20.00",
      online: false,
    },
    {
      id: 4,
      dueDate: "",
      date: "Jan 16, 2026 @ 11:30 AM",
      duration: "01:00",
      status: "Scheduled",
      price: "$20.00",
      owing: "$20.00",
      online: false,
    },
    {
      id: 5,
      dueDate: "",
      date: "Jan 23, 2026 @ 11:30 AM",
      duration: "01:00",
      status: "Scheduled",
      price: "$20.00",
      owing: "$20.00",
      online: false,
    },
    {
      id: 6,
      dueDate: "Jan 15, 2026",
      date: "Feb 06, 2026 @ 11:30 AM",
      duration: "01:00",
      status: "Scheduled",
      price: "$20.00",
      owing: "$20.00",
      online: false,
    },
  ],
  history: [
    {
      id: 1,
      message: "Enrolment created for <a href='/students/123'>stu1 nov12</a> in program <a href='/programs/40th-anniversary-piano'>40th Anniversary Piano</a>",
      createdOn: "Nov 14, 2025",
    },
    {
      id: 2,
      message: "Teacher changed from <a href='/teachers/test-teacherseng'>Test teacherseng</a> to <a href='/teachers/sushanthi-aloysius'>Sushanthi s Aloysius</a>",
      createdOn: "Jan 01, 2026",
    },
    {
      id: 3,
      message: "Rate updated to $20.00 from Nov 14, 2025 to Feb 28, 2026",
      createdOn: "Nov 14, 2025",
    },
    {
      id: 4,
      message: "Schedule updated: Day changed to Friday, Time set to 11:30 AM",
      createdOn: "Nov 14, 2025",
    },
    {
      id: 5,
      message: "Payment frequency set to Monthly",
      createdOn: "Nov 14, 2025",
    },
    {
      id: 6,
      message: "Auto renewal disabled for this enrolment",
      createdOn: "Nov 14, 2025",
    },
  ],
};

