import { EnrolmentRow } from "../enrolmentsListing.api";

export const mockEnrolmentData: EnrolmentRow[] = [
  {
    id: 1,
    program: "40th Anniversary Piano",
    student: "stu1 nov18",
    teacher: "Test teacherseng",
    autoRenewal: "Disabled",
    startDate: "Nov 17, 2025",
    endDate: "Mar 09, 2026",
    lessonsRemaining: 12,
  },
  {
    id: 2,
    program: "40th Anniversary Piano",
    student: "stu3 nov7",
    teacher: "Test teacherseng",
    autoRenewal: "Enabled",
    startDate: "Nov 03, 2025",
    endDate: "Dec 27, 2027",
    lessonsRemaining: 98,
  },
  {
    id: 3,
    program: "40th Anniversary Piano",
    student: "stu1 nov12",
    teacher: "Test teacherseng, Sushanthi s Aloysius",
    autoRenewal: "Disabled",
    startDate: "Nov 14, 2025",
    endDate: "Feb 06, 2026",
    lessonsRemaining: 7,
  },
  {
    id: 4,
    program: "Band",
    student: "Anna Winston",
    teacher: "Daniel Clain",
    autoRenewal: "Disabled",
    startDate: "Oct 18, 2025",
    endDate: "Jan 03, 2026",
    lessonsRemaining: 3,
  },
  {
    id: 5,
    program: "Band",
    student: "Sierra Ackerman",
    teacher: "Daniel Clain",
    autoRenewal: "Enabled",
    startDate: "Nov 14, 2023",
    endDate: "Nov 23, 2027",
    lessonsRemaining: 94,
  },
  {
    id: 6,
    program: "Bass Guitar",
    student: "Sofi test",
    teacher: "Alexander Hamilton",
    autoRenewal: "Disabled",
    startDate: "Jan 26, 2022",
    endDate: "Jan 26, 2028",
    lessonsRemaining: 102,
  },
  {
    id: 7,
    program: "Bass Guitar",
    student: "Hubert Amburos",
    teacher: "Art Tatum",
    autoRenewal: "Enabled",
    startDate: "Nov 17, 2025",
    endDate: "Mar 09, 2026",
    lessonsRemaining: 11,
  },
  {
    id: 8,
    program: "Cello",
    student: "stu1 nov18",
    teacher: "Art Tatum, Alexander Hamilton, Alexander Hamilton",
    autoRenewal: "Disabled",
    startDate: "Oct 18, 2025",
    endDate: "Jan 03, 2026",
    lessonsRemaining: 3,
  },
  {
    id: 9,
    program: "Clarinet",
    student: "Anna Winston",
    teacher: "Daniel Clain",
    autoRenewal: "Enabled",
    startDate: "Nov 14, 2023",
    endDate: "Nov 23, 2027",
    lessonsRemaining: 94,
  },
  {
    id: 10,
    program: "40th Anniversary Piano",
    student: "Sierra Ackerman",
    teacher: "Test teacherseng",
    autoRenewal: "Disabled",
    startDate: "Jan 26, 2022",
    endDate: "Jan 26, 2028",
    lessonsRemaining: 102,
  },
  {
    id: 11,
    program: "Band",
    student: "Sofi test",
    teacher: "Alexander Hamilton",
    autoRenewal: "Enabled",
    startDate: "Nov 17, 2025",
    endDate: "Mar 09, 2026",
    lessonsRemaining: 12,
  },
  {
    id: 12,
    program: "Bass Guitar",
    student: "Hubert Amburos",
    teacher: "Art Tatum",
    autoRenewal: "Disabled",
    startDate: "Nov 03, 2025",
    endDate: "Dec 27, 2027",
    lessonsRemaining: 98,
  },
  {
    id: 13,
    program: "Cello",
    student: "stu1 nov18",
    teacher: "Daniel Clain",
    autoRenewal: "Disabled",
    startDate: "Nov 14, 2025",
    endDate: "Feb 06, 2026",
    lessonsRemaining: 7,
  },
  {
    id: 14,
    program: "Clarinet",
    student: "Anna Winston",
    teacher: "Test teacherseng, Sushanthi s Aloysius",
    autoRenewal: "Enabled",
    startDate: "Oct 18, 2025",
    endDate: "Jan 03, 2026",
    lessonsRemaining: 3,
  },
  {
    id: 15,
    program: "40th Anniversary Piano",
    student: "Sierra Ackerman",
    teacher: "Alexander Hamilton",
    autoRenewal: "Disabled",
    startDate: "Nov 14, 2023",
    endDate: "Nov 23, 2027",
    lessonsRemaining: 94,
  },
  {
    id: 16,
    program: "Band",
    student: "Sofi test",
    teacher: "Art Tatum, Alexander Hamilton",
    autoRenewal: "Enabled",
    startDate: "Jan 26, 2022",
    endDate: "Jan 26, 2028",
    lessonsRemaining: 102,
  },
  {
    id: 17,
    program: "Bass Guitar",
    student: "Hubert Amburos",
    teacher: "Daniel Clain",
    autoRenewal: "Disabled",
    startDate: "Nov 17, 2025",
    endDate: "Mar 09, 2026",
    lessonsRemaining: 11,
  },
  {
    id: 18,
    program: "Cello",
    student: "stu1 nov18",
    teacher: "Test teacherseng",
    autoRenewal: "Enabled",
    startDate: "Oct 18, 2025",
    endDate: "Jan 03, 2026",
    lessonsRemaining: 3,
  },
  {
    id: 19,
    program: "Clarinet",
    student: "Anna Winston",
    teacher: "Alexander Hamilton",
    autoRenewal: "Disabled",
    startDate: "Nov 14, 2023",
    endDate: "Nov 23, 2027",
    lessonsRemaining: 94,
  },
  {
    id: 20,
    program: "40th Anniversary Piano",
    student: "Sierra Ackerman",
    teacher: "Art Tatum",
    autoRenewal: "Enabled",
    startDate: "Jan 26, 2022",
    endDate: "Jan 26, 2028",
    lessonsRemaining: 102,
  },
];

