// Location-based feature flags utility
// This can be extended to fetch from an API or database in the future

export interface LocationFlags {
  [location: string]: {
    [feature: string]: 'modern' | 'legacy' | 'disabled';
  };
}

// Default location flags - can be moved to a database/API later
export const DEFAULT_LOCATION_FLAGS: LocationFlags = {
  'bolton': {
    dashboard: 'legacy',
    schedule: 'legacy',
    enrolments: 'legacy',
    students: 'legacy',
    customers: 'legacy',
    teachers: 'legacy',
    privateLessons: 'legacy',
    groupCourses: 'legacy',
    unscheduledLessons: 'legacy',
    recurringPayments: 'legacy',
    paymentPreferences: 'legacy',
    invoices: 'legacy',
    payments: 'legacy',
    reports: 'legacy',
    releaseNotes: 'legacy',
    items: 'legacy',
    admin: 'legacy',
    setup: 'legacy',
    timeline: 'legacy',
  },
  'burlington': {
    dashboard: 'modern',
    schedule: 'modern',
    enrolments: 'legacy',
    students: 'legacy',
    customers: 'legacy',
    teachers: 'legacy',
    privateLessons: 'legacy',
    groupCourses: 'legacy',
    unscheduledLessons: 'legacy',
    recurringPayments: 'legacy',
    paymentPreferences: 'legacy',
    invoices: 'legacy',
    payments: 'legacy',
    reports: 'legacy',
    releaseNotes: 'legacy',
    items: 'legacy',
    admin: 'legacy',
    setup: 'legacy',
    timeline: 'legacy',
  },
  'maple': {
    dashboard: 'legacy',
    schedule: 'legacy',
    enrolments: 'legacy',
    students: 'legacy',
    customers: 'legacy',
    teachers: 'legacy',
    privateLessons: 'legacy',
    groupCourses: 'legacy',
    unscheduledLessons: 'legacy',
    recurringPayments: 'legacy',
    paymentPreferences: 'legacy',
    invoices: 'legacy',
    payments: 'legacy',
    reports: 'legacy',
    releaseNotes: 'legacy',
    items: 'legacy',
    admin: 'legacy',
    setup: 'legacy',
    timeline: 'legacy',
  },
  'markham': {
    dashboard: 'legacy',
    schedule: 'legacy',
    enrolments: 'legacy',
    students: 'legacy',
    customers: 'legacy',
    teachers: 'legacy',
    privateLessons: 'legacy',
    groupCourses: 'legacy',
    unscheduledLessons: 'legacy',
    recurringPayments: 'legacy',
    paymentPreferences: 'legacy',
    invoices: 'legacy',
    payments: 'legacy',
    reports: 'legacy',
    releaseNotes: 'legacy',
    items: 'legacy',
    admin: 'legacy',
    setup: 'legacy',
    timeline: 'legacy',
  },
  'newmarket': {
    dashboard: 'legacy',
    schedule: 'legacy',
    enrolments: 'legacy',
    students: 'legacy',
    customers: 'legacy',
    teachers: 'legacy',
    privateLessons: 'legacy',
    groupCourses: 'legacy',
    unscheduledLessons: 'legacy',
    recurringPayments: 'legacy',
    paymentPreferences: 'legacy',
    invoices: 'legacy',
    payments: 'legacy',
    reports: 'legacy',
    releaseNotes: 'legacy',
    items: 'legacy',
    admin: 'legacy',
    setup: 'legacy',
    timeline: 'legacy',
  },
  'nobleton': {
    dashboard: 'legacy',
    schedule: 'legacy',
    enrolments: 'legacy',
    students: 'legacy',
    customers: 'legacy',
    teachers: 'legacy',
    privateLessons: 'legacy',
    groupCourses: 'legacy',
    unscheduledLessons: 'legacy',
    recurringPayments: 'legacy',
    paymentPreferences: 'legacy',
    invoices: 'legacy',
    payments: 'legacy',
    reports: 'legacy',
    releaseNotes: 'legacy',
    items: 'legacy',
    admin: 'legacy',
    setup: 'legacy',
    timeline: 'legacy',
  },
  'north-brampton': {
    dashboard: 'legacy',
    schedule: 'legacy',
    enrolments: 'legacy',
    students: 'legacy',
    customers: 'legacy',
    teachers: 'legacy',
    privateLessons: 'legacy',
    groupCourses: 'legacy',
    unscheduledLessons: 'legacy',
    recurringPayments: 'legacy',
    paymentPreferences: 'legacy',
    invoices: 'legacy',
    payments: 'legacy',
    reports: 'legacy',
    releaseNotes: 'legacy',
    items: 'legacy',
    admin: 'legacy',
    setup: 'legacy',
    timeline: 'legacy',
  },
  'richmond-hill': {
    dashboard: 'legacy',
    schedule: 'legacy',
    enrolments: 'legacy',
    students: 'legacy',
    customers: 'legacy',
    teachers: 'legacy',
    privateLessons: 'legacy',
    groupCourses: 'legacy',
    unscheduledLessons: 'legacy',
    recurringPayments: 'legacy',
    paymentPreferences: 'legacy',
    invoices: 'legacy',
    payments: 'legacy',
    reports: 'legacy',
    releaseNotes: 'legacy',
    items: 'legacy',
    admin: 'legacy',
    setup: 'legacy',
    timeline: 'legacy',
  },
  'south-brampton': {
    dashboard: 'legacy',
    schedule: 'legacy',
    enrolments: 'legacy',
    students: 'legacy',
    customers: 'legacy',
    teachers: 'legacy',
    privateLessons: 'legacy',
    groupCourses: 'legacy',
    unscheduledLessons: 'legacy',
    recurringPayments: 'legacy',
    paymentPreferences: 'legacy',
    invoices: 'legacy',
    payments: 'legacy',
    reports: 'legacy',
    releaseNotes: 'legacy',
    items: 'legacy',
    admin: 'legacy',
    setup: 'legacy',
    timeline: 'legacy',
  },
  'training-location': {
    dashboard: 'modern',
    schedule: 'modern',
    enrolments: 'legacy',
    students: 'legacy',
    customers: 'legacy',
    teachers: 'legacy',
    privateLessons: 'legacy',
    groupCourses: 'legacy',
    unscheduledLessons: 'legacy',
    recurringPayments: 'legacy',
    paymentPreferences: 'legacy',
    invoices: 'legacy',
    payments: 'legacy',
    reports: 'legacy',
    releaseNotes: 'legacy',
    items: 'legacy',
    admin: 'legacy',
    setup: 'legacy',
    timeline: 'legacy',
  },
  'west-brampton': {
    dashboard: 'legacy',
    schedule: 'legacy',
    enrolments: 'legacy',
    students: 'legacy',
    customers: 'legacy',
    teachers: 'legacy',
    privateLessons: 'legacy',
    groupCourses: 'legacy',
    unscheduledLessons: 'legacy',
    recurringPayments: 'legacy',
    paymentPreferences: 'legacy',
    invoices: 'legacy',
    payments: 'legacy',
    reports: 'legacy',
    releaseNotes: 'legacy',
    items: 'legacy',
    admin: 'legacy',
    setup: 'legacy',
    timeline: 'legacy',
  },
  'woodbridge': {
    dashboard: 'legacy',
    schedule: 'legacy',
    enrolments: 'legacy',
    students: 'legacy',
    customers: 'legacy',
    teachers: 'legacy',
    privateLessons: 'legacy',
    groupCourses: 'legacy',
    unscheduledLessons: 'legacy',
    recurringPayments: 'legacy',
    paymentPreferences: 'legacy',
    invoices: 'legacy',
    payments: 'legacy',
    reports: 'legacy',
    releaseNotes: 'legacy',
    items: 'legacy',
    admin: 'legacy',
    setup: 'legacy',
    timeline: 'legacy',
  },
};

// Helper functions
export const isFeatureEnabled = (location: string, feature: string): boolean => {
  const locationFlags = DEFAULT_LOCATION_FLAGS[location];
  if (!locationFlags) return false;
  
  const featureFlag = locationFlags[feature];
  return featureFlag !== 'disabled';
};

export const getFeatureSource = (location: string, feature: string): 'modern' | 'legacy' => {
  const locationFlags = DEFAULT_LOCATION_FLAGS[location];
  if (!locationFlags) return 'legacy';
  
  const featureFlag = locationFlags[feature];
  return featureFlag === 'modern' ? 'modern' : 'legacy';
};

// Future: API functions to manage flags
export const updateLocationFlag = async (
  location: string, 
  feature: string, 
  value: 'modern' | 'legacy' | 'disabled'
): Promise<void> => {
  // TODO: Implement API call to update flags
  console.log(`Updating ${location}.${feature} to ${value}`);
};

export const getLocationFlags = async (location: string): Promise<LocationFlags[string]> => {
  // TODO: Implement API call to fetch flags
  return DEFAULT_LOCATION_FLAGS[location] || {};
};
