name: Dev Web Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'platform_tools_new/**'
      - '.github/**'
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  contents: read
  packages: write
  actions: write

env:
  TF_VERSION: '1.9.1'
  TF_WORKING_DIR: 'platform_tools_new/web-manifest'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKER_BUILDKIT: 1

jobs:
  push-store-image:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.commit.outputs.short }}
    defaults:
        run:
            working-directory: './'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v2

      # Load build-time envs (NEXT_PUBLIC_*)
      - name: Load build env vars
        run: |
          while IFS=": " read -r key value; do
            if [[ -n "$key" && -n "$value" ]]; then
              echo "$key=$value" >> $GITHUB_ENV
            fi
          done < platform_tools_new/web-env/dev.txt

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Store Image (cached)
        run: |
          IMAGE_NAME=ghcr.io/arcadia-music-academy/smw-web:${{ steps.commit.outputs.short }}

          docker buildx build \
            --build-arg NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
            --build-arg NEXT_PUBLIC_LEGACY_URL=$NEXT_PUBLIC_LEGACY_URL \
            --build-arg NEXT_PUBLIC_ENV=$NEXT_PUBLIC_ENV \
            --build-arg NEXT_PUBLIC_OPENREPLAY_PROJECT_KEY=$NEXT_PUBLIC_OPENREPLAY_PROJECT_KEY \
            --build-arg NEXT_PUBLIC_OPENREPLAY_INGEST_POINT=$NEXT_PUBLIC_OPENREPLAY_INGEST_POINT \
            --cache-from=type=registry,ref=ghcr.io/arcadia-music-academy/smw-web:buildcache \
            --cache-to=type=registry,ref=ghcr.io/arcadia-music-academy/smw-web:buildcache,mode=max \
            -t $IMAGE_NAME \
            -t ghcr.io/arcadia-music-academy/smw-web:latest \
            --push .

      - name: Show Docker image info
        run: |
          echo "Image pushed:"
          echo "Tag: ${{ steps.commit.outputs.short }}"

  tofu-deployment:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
    name: tofu deployment
    needs: push-store-image
    runs-on: ubuntu-latest
    env:
      TF_VAR_github_username: ${{ secrets.SMW_GITHUB_USERNAME }}
      TF_VAR_github_pat_token: ${{ secrets.PAT_TOKEN }}
      TF_VAR_github_email_id: ${{ secrets.SMW_GITHUB_EMAIL_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup tofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ env.TF_VERSION }}

      - name: tofu Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          tofu init \
            -backend-config "key=web-app-dev.tfstate" \
            -backend-config "access_key=${{ env.AWS_ACCESS_KEY_ID }}" \
            -backend-config "secret_key=${{ env.AWS_SECRET_ACCESS_KEY }}" \
            -backend-config "bucket=smw-dev-infra"

      - name: tofu Format
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: tofu fmt -check

      - name: tofu Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: tofu validate

      - name: Install s3cmd
        run: |
          sudo apt-get update
          sudo apt-get install -y s3cmd
          s3cmd --version

      - name: Configure s3cmd
        run: |
          cat > ~/.s3cfg <<EOF
          access_key = ${{ env.AWS_ACCESS_KEY_ID }}
          secret_key = ${{ env.AWS_SECRET_ACCESS_KEY }}
          host_base = nbg1.your-objectstorage.com
          host_bucket = nbg1.your-objectstorage.com
          bucket_location = eu-central-1
          use_https = True
          check_ssl_certificate = True
          check_ssl_hostname = True
          cloudfront_host = cloudfront.amazonaws.com
          website_endpoint = http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
          EOF

      - name: Downloading Kubeconfig from the object storage
        run: |
          mkdir -p ~/.kube
          s3cmd get s3://smw-dev-configurations/kubeconfig/config-k3s ~/.kube/config-k3s

      - name: Runtime Configuration
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          sed -i -E "s|^web_docker_image[[:space:]]*=.*|web_docker_image = \"ghcr.io/arcadia-music-academy/smw-web:${{ needs.push-store-image.outputs.image_tag }}\"|" tfvars/dev.tfvars

      - name: tofu Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: tofu plan -var-file="tfvars/dev.tfvars"

      - name: tofu Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          tofu apply -auto-approve -var-file="tfvars/dev.tfvars"

      - name: Save tofu outputs to file
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          tofu output -json > tofu-outputs.json

      - name: Upload tofu outputs
        uses: actions/upload-artifact@v4
        with:
          name: web-tofu-outputs
          path: ${{ env.TF_WORKING_DIR }}/tofu-outputs.json

      - name: Notify Slack (Apply)
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEV }}
        with:
          status: ${{ job.status }}
          text: "${{ job.status == 'success' && format('✅ {0} deployed on dev!', github.workflow) || job.status == 'failure' && format('❌ {0} deployment failed on dev!', github.workflow) || format('⚠️ {0} deployment cancelled on dev!', github.workflow) }}"
          custom_payload: |
            {
              attachments: [{
                color: "${{ job.status == 'success' && 'good' || job.status == 'failure' && 'danger' || 'warning' }}",
                fields: [{
                  title: "Workflow",
                  value: "${{ github.workflow }}",
                  short: true
                }, {
                  title: "Author",
                  value: "${{ github.triggering_actor || github.actor }}",
                  short: true
                }, {
                  title: "Status",
                  value: "${{ job.status }}",
                  short: true
                }]
              }]
            }
        if: always()

  tofu-destroy:
    if: ${{ github.event.inputs.action == 'destroy' }}
    name: tofu Destroy
    runs-on: ubuntu-latest
    env:
      TF_VAR_github_username: ${{ secrets.SMW_GITHUB_USERNAME }}
      TF_VAR_github_pat_token: ${{ secrets.PAT_TOKEN }}
      TF_VAR_github_email_id: ${{ secrets.SMW_GITHUB_EMAIL_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup tofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ env.TF_VERSION }}

      - name: tofu Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          tofu init \
            -backend-config "key=web-app-dev.tfstate" \
            -backend-config "access_key=${{ env.AWS_ACCESS_KEY_ID }}" \
            -backend-config "secret_key=${{ env.AWS_SECRET_ACCESS_KEY }}" \
            -backend-config "bucket=smw-dev-infra"

      - name: Install s3cmd
        run: |
          sudo apt-get update
          sudo apt-get install -y s3cmd
          s3cmd --version

      - name: Configure s3cmd
        run: |
          cat > ~/.s3cfg <<EOF
          access_key = ${{ env.AWS_ACCESS_KEY_ID }}
          secret_key = ${{ env.AWS_SECRET_ACCESS_KEY }}
          host_base = nbg1.your-objectstorage.com
          host_bucket = nbg1.your-objectstorage.com
          bucket_location = eu-central-1
          use_https = True
          check_ssl_certificate = True
          check_ssl_hostname = True
          cloudfront_host = cloudfront.amazonaws.com
          website_endpoint = http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
          EOF

      - name: Downloading Kubeconfig from the object storage
        run: |
          mkdir -p ~/.kube
          s3cmd get s3://smw-dev-configurations/kubeconfig/config-k3s ~/.kube/config-k3s

      - name: tofu Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          tofu destroy -auto-approve -var-file="tfvars/dev.tfvars"

      - name: Notify Slack (Destroy)
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEV }}
        with:
          status: ${{ job.status }}
          text: "${{ job.status == 'success' && format('✅ {0} destroyed on dev!', github.workflow) || job.status == 'failure' && format('❌ {0} destroy failed on dev!', github.workflow) || format('⚠️ {0} destroy cancelled on dev!', github.workflow) }}"
          custom_payload: |
            {
              attachments: [{
                color: "${{ job.status == 'success' && 'good' || job.status == 'failure' && 'danger' || 'warning' }}",
                fields: [{
                  title: "Workflow",
                  value: "${{ github.workflow }}",
                  short: true
                }, {
                  title: "Author",
                  value: "${{ github.triggering_actor || github.actor }}",
                  short: true
                }, {
                  title: "Status",
                  value: "${{ job.status }}",
                  short: true
                }]
              }]
            }
        if: always()
